apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hpcmlx-prod
  region: us-east-1
  version: "1.28"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: HighlyAvailable

managedNodeGroups:
  - name: hpcmlx-nodes
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 30 
    ssh:
      allow: false
    labels:
      role: worker
    tags:
      Environment: production
      Application: hpcmlx
      ManagedBy: eksctl

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

